import { LogIn, UserPlus, X } from "lucide-react";
import { useEffect, useRef } from "react";

const AuthPromptModal = ({ prompt, onClose, onSignIn, onCreateAccount }) => {
  const cancelRef = useRef(null);
  useEffect(() => { if (!prompt) return; cancelRef.current?.focus(); const escape = (event) => event.key === "Escape" && onClose(); document.addEventListener("keydown", escape); return () => document.removeEventListener("keydown", escape); }, [prompt, onClose]);
  if (!prompt) return null;
  return <div className="fixed inset-0 z-[110] grid place-items-center bg-slate-950/60 p-4 backdrop-blur-sm" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section role="dialog" aria-modal="true" aria-labelledby="auth-prompt-title" className="w-full max-w-md animate-[fadeIn_.18s_ease-out] rounded-[2rem] border border-slate-200 bg-white p-6 shadow-2xl sm:p-7"><div className="flex items-start justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-orange-50 text-orange-600"><LogIn size={23}/></span><button type="button" onClick={onClose} aria-label="Close sign-in prompt" className="rounded-xl p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700"><X size={20}/></button></div><h2 id="auth-prompt-title" className="mt-5 text-xl font-black text-slate-950">{prompt.title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{prompt.description}</p><div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button ref={cancelRef} type="button" onClick={onClose} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-700 hover:bg-slate-50">Cancel</button>{prompt.allowSignup && <button type="button" onClick={onCreateAccount} className="inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold text-orange-600 hover:bg-orange-50"><UserPlus size={17}/>Create account</button>}<button type="button" onClick={onSignIn} className="inline-flex items-center justify-center gap-2 rounded-xl bg-orange-500 px-4 py-2.5 text-sm font-bold text-white hover:bg-orange-600"><LogIn size={17}/>Sign In</button></div></section></div>;
};
export default AuthPromptModal;
