import { useContext, useEffect, useState } from "react";
import { ImagePlus, LoaderCircle } from "lucide-react";
import { toast } from "sonner";
import { AppContext } from "../../context/AppContext";
import { Field, FormSection, PageIntro, inputClass } from "./AdminUI";

const AddCategory = () => {
  const { axios, navigate, loading, setLoading, fetchCategories } = useContext(AppContext); const [name, setName] = useState(""); const [file, setFile] = useState(null); const [preview, setPreview] = useState("");
  useEffect(() => () => preview && URL.revokeObjectURL(preview), [preview]);
  const chooseFile = (event) => { const selected = event.target.files?.[0]; if (!selected) return; if (!selected.type.startsWith("image/")) return toast.error("Choose an image file"); setFile(selected); setPreview(URL.createObjectURL(selected)); };
  const submit = async (event) => { event.preventDefault(); if (!file) return toast.error("Choose a category image"); try { setLoading(true); const { data } = await axios.post("/api/category/add", { name, image: file }, { headers: { "Content-Type": "multipart/form-data" } }); if (!data.success) throw new Error(data.message); toast.success(data.message); await fetchCategories(); navigate("/admin/categories"); } catch (error) { toast.error(error.response?.data?.message || error.message || "Unable to create category"); } finally { setLoading(false); } };
  return <form onSubmit={submit} className="mx-auto max-w-4xl space-y-6"><PageIntro eyebrow="New category" description="Create a customer-facing category for organizing related menu items."/><div className="grid gap-6 lg:grid-cols-[1fr_320px]"><FormSection title="Basic information" description="Choose a clear name customers can quickly understand."><Field label="Category name" required hint="Use a short descriptive label, such as Breakfast or Desserts."><input value={name} onChange={(e) => setName(e.target.value)} required placeholder="e.g. Main dishes" className={inputClass}/></Field></FormSection><FormSection title="Category image" description="Upload a square image for the category card."><input id="category-image" type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={chooseFile} className="sr-only"/><label htmlFor="category-image" className="group grid min-h-48 cursor-pointer place-items-center overflow-hidden rounded-2xl border-2 border-dashed border-slate-300 bg-slate-50 text-center transition hover:border-orange-400 hover:bg-orange-50/40 focus-within:ring-4 focus-within:ring-orange-100">{preview ? <img src={preview} alt="Category preview" className="h-52 w-full object-cover"/> : <span className="p-6"><ImagePlus className="mx-auto text-slate-400 group-hover:text-orange-500" size={32}/><span className="mt-3 block text-sm font-semibold text-slate-700">Choose an image</span><span className="mt-1 block text-xs text-slate-400">PNG, JPG, WEBP or GIF · max 5 MB</span></span>}</label>{file && <p className="mt-3 truncate text-xs text-slate-500">{file.name}</p>}</FormSection></div><div className="flex flex-col-reverse justify-end gap-3 sm:flex-row"><button type="button" onClick={() => navigate("/admin/categories")} disabled={loading} className="h-12 rounded-xl border border-slate-200 px-5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Cancel</button><button disabled={loading} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-orange-500 px-6 text-sm font-semibold text-white shadow-sm hover:bg-orange-600 disabled:opacity-60">{loading && <LoaderCircle size={18} className="animate-spin"/>}{loading ? "Creating category" : "Create category"}</button></div></form>;
};
export default AddCategory;
