import { AlertCircle, ChevronLeft, ChevronRight, Inbox, LoaderCircle, Search, X } from "lucide-react";
import { createElement, useEffect, useMemo, useState } from "react";
/* eslint-disable react-refresh/only-export-components */

export const PageIntro = ({ eyebrow, description, action }) => <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm font-semibold text-orange-600">{eyebrow}</p><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">{description}</p></div>{action}</div>;

export const Card = ({ children, className = "" }) => <section className={`rounded-2xl border border-slate-200 bg-white shadow-sm ${className}`}>{children}</section>;

export const KPICard = ({ label, value, icon, helper, loading }) => <Card className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium text-slate-500">{label}</p>{loading ? <div className="mt-3 h-9 w-20 animate-pulse rounded-lg bg-slate-200" /> : <p className="mt-2 text-3xl font-bold tracking-tight text-slate-900">{value}</p>}<p className="mt-2 text-xs text-slate-400">{helper}</p></div><span className="grid size-11 place-items-center rounded-xl bg-orange-50 text-orange-600">{createElement(icon, { size: 21 })}</span></div></Card>;

const statusStyles = { "Payment Pending": "bg-amber-50 text-amber-700 ring-amber-600/20", Paid: "bg-emerald-50 text-emerald-700 ring-emerald-600/20", Pending: "bg-amber-50 text-amber-700 ring-amber-600/20", Preparing: "bg-blue-50 text-blue-700 ring-blue-600/20", Approved: "bg-emerald-50 text-emerald-700 ring-emerald-600/20", Delivered: "bg-emerald-50 text-emerald-700 ring-emerald-600/20", Cancelled: "bg-red-50 text-red-700 ring-red-600/20", Available: "bg-emerald-50 text-emerald-700 ring-emerald-600/20", Unavailable: "bg-slate-100 text-slate-600 ring-slate-500/20" };
export const StatusBadge = ({ status }) => <span className={`inline-flex items-center rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ring-inset ${statusStyles[status] || "bg-slate-100 text-slate-700 ring-slate-500/20"}`}><span className="mr-1.5 size-1.5 rounded-full bg-current" />{status}</span>;

export const FilterBar = ({ search, onSearch, placeholder, status, onStatus, statuses = [], onClear, children }) => <Card className="mb-5 p-3"><div className="flex flex-col gap-3 md:flex-row"><label className="relative min-w-0 flex-1"><span className="sr-only">Search</span><Search size={18} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={(e) => onSearch(e.target.value)} placeholder={placeholder} className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 pr-10 text-sm outline-none transition focus:border-orange-400 focus:bg-white focus:ring-4 focus:ring-orange-100"/>{search && <button type="button" onClick={() => onSearch("")} aria-label="Clear search" className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-700"><X size={17}/></button>}</label>{statuses.length > 0 && <select value={status} onChange={(e) => onStatus(e.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-medium text-slate-700 outline-none focus:border-orange-400 focus:ring-4 focus:ring-orange-100"><option value="">All statuses</option>{statuses.map((item) => <option key={item} value={item}>{item}</option>)}</select>}{children}{(search || status) && <button type="button" onClick={onClear} className="h-11 rounded-xl px-4 text-sm font-semibold text-slate-600 hover:bg-slate-100">Clear filters</button>}</div></Card>;

export const TableSkeleton = ({ columns = 5 }) => <div className="animate-pulse">{Array.from({ length: 5 }).map((_, row) => <div key={row} className="grid gap-4 border-t border-slate-100 px-5 py-5" style={{ gridTemplateColumns: `repeat(${columns}, minmax(0, 1fr))` }}>{Array.from({ length: columns }).map((__, column) => <div key={column} className="h-4 rounded bg-slate-200" />)}</div>)}</div>;
export const EmptyState = ({ title, description, action }) => <div className="grid place-items-center px-6 py-16 text-center"><span className="grid size-14 place-items-center rounded-2xl bg-slate-100 text-slate-400"><Inbox size={26}/></span><h3 className="mt-4 font-bold text-slate-900">{title}</h3><p className="mt-1 max-w-sm text-sm text-slate-500">{description}</p>{action && <div className="mt-5">{action}</div>}</div>;
export const ErrorState = ({ onRetry }) => <div className="grid place-items-center px-6 py-16 text-center"><AlertCircle className="text-red-500" size={32}/><h3 className="mt-3 font-bold text-slate-900">Unable to load data</h3><p className="mt-1 text-sm text-slate-500">Something went wrong while retrieving the information.</p><button onClick={onRetry} className="mt-5 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Try again</button></div>;

export const usePagination = (items, pageSize = 8) => { const [page, setPage] = useState(1); const [size, setSize] = useState(pageSize); const pages = Math.max(1, Math.ceil(items.length / size)); useEffect(() => { if (page > pages) setPage(pages); }, [page, pages]); return { page, setPage, size, setSize, pages, items: useMemo(() => items.slice((page - 1) * size, page * size), [items, page, size]) }; };
export const Pagination = ({ page, pages, size, total, onPage, onSize }) => { const start = total ? (page - 1) * size + 1 : 0; const end = Math.min(page * size, total); return <div className="flex flex-col items-center justify-between gap-3 border-t border-slate-200 px-4 py-4 text-sm sm:flex-row"><p className="text-slate-500">Showing <b className="text-slate-700">{start}–{end}</b> of <b className="text-slate-700">{total}</b></p><div className="flex items-center gap-2"><select value={size} onChange={(e) => onSize(Number(e.target.value))} className="h-9 rounded-lg border border-slate-200 px-2 text-xs"><option value={8}>8 rows</option><option value={12}>12 rows</option><option value={20}>20 rows</option></select><button disabled={page === 1} onClick={() => onPage(page - 1)} aria-label="Previous page" className="grid size-9 place-items-center rounded-lg border border-slate-200 disabled:opacity-40"><ChevronLeft size={17}/></button><span className="min-w-16 text-center font-semibold">{page} / {pages}</span><button disabled={page === pages} onClick={() => onPage(page + 1)} aria-label="Next page" className="grid size-9 place-items-center rounded-lg border border-slate-200 disabled:opacity-40"><ChevronRight size={17}/></button></div></div>; };

export const ConfirmActionModal = ({ open, title, description, confirmLabel, destructive = false, loading, onCancel, onConfirm }) => { if (!open) return null; return <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/55 p-4 backdrop-blur-sm"><div role="dialog" aria-modal="true" className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-bold text-slate-900">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p><div className="mt-7 flex justify-end gap-3"><button onClick={onCancel} disabled={loading} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Cancel</button><button onClick={onConfirm} disabled={loading} className={`inline-flex min-w-24 items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50 ${destructive ? "bg-red-600" : "bg-orange-500"}`}>{loading && <LoaderCircle size={16} className="animate-spin"/>}{confirmLabel}</button></div></div></div>; };

export const inputClass = "h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-3.5 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-orange-400 focus:bg-white focus:ring-4 focus:ring-orange-100 disabled:cursor-not-allowed disabled:opacity-60";
export const Field = ({ label, required, hint, children }) => <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}{required && <span className="ml-1 text-orange-600">*</span>}</span>{children}{hint && <span className="mt-1.5 block text-xs text-slate-400">{hint}</span>}</label>;
export const FormSection = ({ title, description, children }) => <Card className="p-5 sm:p-6"><div className="mb-5"><h2 className="font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div>{children}</Card>;
